export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE_BASIC_INFO = 'FETCH_MOVIE_BASIC_INFO';
export const FETCH_MOVIE_ALT_TITLES = 'FETCH_MOVIE_ALT_TITLES';
export const FETCH_MOVIE_VIDEOS = 'FETCH_MOVIE_VIDEOS';
export const FETCH_MOVIE_IMAGES = 'FETCH_MOVIE_IMAGES';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';